version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: roadmap-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: roadmap_user
      POSTGRES_PASSWORD: roadmap_password
      POSTGRES_DB: developer_roadmap
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roadmap_user -d developer_roadmap"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: