[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm', 'postgresql']

[phases.install]
cmds = [
    'cd backend && npm ci',
    'cd frontend && npm ci'
]

[phases.build]
cmds = [
    'cd backend && npx prisma generate && npm run build',
    'cd frontend && npm run build'
]

[start]
cmd = 'cd backend && node dist/index.js'

[variables]
NODE_ENV = 'production'